Repository GSG-G11/Indonate, pull requests merged in 2022-05, with the labels that each got.

#78 fix structure of form an item should contain one child which is dateP…
  client/package-lock.json
  client/package.json
  client/src/components/donateForm/DonateButton.jsx
  client/src/components/donateForm/DonationForm.jsx
Labels: Done

#71 Header landing page
  client/src/App.js
  client/src/components/assets/images/landingPageHeader.png
  client/src/components/headerLandingPage/index.jsx
  client/src/components/headerLandingPage/style.css
  client/src/components/index.jsx
  server/controllers/compaignRouter/statistics.ts
  server/tests/route.test.ts
Labels: Awaiting Review, Frontend

#61 all campaignes page
  client/craco.config.js
  client/src/App.js
  client/src/assets/images/bgImg-comments.jpeg
  client/src/assets/images/children.png
  client/src/assets/images/our-mission-background.jpg
  client/src/assets/images/sign-up-bg.png
  client/src/components/DisplayCampaigns/index.jsx
  client/src/components/DisplayCampaigns/style.css
  client/src/components/HeaderAllCampaigns/index.jsx
  client/src/components/HeaderAllCampaigns/style.css
  client/src/components/OurMission/style.less
  client/src/components/Review/style.css
  client/src/components/campaignList/index.jsx
  client/src/components/campaignList/style.css
  client/src/components/common/campaignCard/index.jsx
  client/src/components/common/campaignCard/index.less
  client/src/components/filterCampaigns/index.jsx
  client/src/components/filterCampaigns/style.less
  client/src/components/index.jsx
  client/src/components/signUp/style.css
  client/src/components/signUp/style.less
  client/src/pages/Campaigns.jsx
  client/src/pages/index.jsx
  server/controllers/compaignRouter/campaignes.ts
  server/utils/validation/QueryValidation.ts
Labels: Awaiting Review

#70 Latest campaigns section landing page
  client/src/App.js
  client/src/components/common/campaignCard/index.jsx
  client/src/components/donateForm/index.jsx
  client/src/components/index.jsx
  client/src/components/latestCampaigns/index.jsx
  client/src/components/latestCampaigns/style.less
Labels: Done

#79 76 one page capmaign
  client/src/App.js
  client/src/components/HeaderAllCampaigns/style.css
  client/src/components/ReportsForm/style.less
  client/src/components/campaignList/index.jsx
  client/src/components/common/campaignCard/index.jsx
  client/src/components/donateForm/DonateButton.jsx
  client/src/pages/Campaign/index.jsx
  client/src/pages/Campaign/style.less
  client/src/pages/Campaigns.jsx
  client/src/pages/index.jsx
  server/controllers/compaignRouter/getCampaignById.ts
  server/controllers/compaignRouter/statistics.ts
  server/database/fakeData/campaigns.json
  server/database/models/campaign.ts
  server/tests/route.test.ts
Labels: Done

#94 93 logout
  client/src/components/Nav/index.jsx
  client/src/components/Nav/style.css
  client/src/components/OurMission/index.jsx
  client/src/components/ReportsForm/index.jsx
  client/src/redux/feature/user/userSlice.js
Labels: Awaiting Review

#83 Footer
  client/src/App.js
  client/src/components/DisplayCampaigns/style.css
  client/src/components/assets/images/footer-logo.svg
  client/src/components/common/footer/index.jsx
  client/src/components/common/footer/style.css
Labels: Awaiting Review

#96 Add loading to campaign card
  client/src/components/DisplayCampaigns/index.jsx
  client/src/components/campaignList/index.jsx
  client/src/components/common/campaignCard/index.jsx
  client/src/components/common/campaignCard/index.less
  client/src/components/donateForm/DonateButton.jsx
  client/src/components/filterCampaigns/index.jsx
  client/src/components/filterCampaigns/style.less
Labels: Awaiting Review

#85 Signin and Signup Form fix
  client/src/components/HeaderLandingPage/index.jsx
  client/src/components/LatestCampaigns/index.jsx
  client/src/components/LatestCampaigns/style.less
  client/src/components/common/CampaignCard/index.jsx
  client/src/components/common/Footer/index.jsx
  client/src/components/common/Footer/style.less
  client/src/components/common/Nav/index.jsx
  client/src/pages/Landing/index.jsx
  client/src/pages/Login/index.jsx
  client/src/pages/Login/index.less
  client/src/pages/Signup/index.jsx
  client/src/pages/Signup/style.less
  client/src/pages/index.jsx
Labels: Awaiting Review

#106 88 delete/donors/id
  server/controllers/admin/donors/deleteDonorById.ts
  server/controllers/admin/index.ts
  server/controllers/index.ts
  server/routes/adminDonor.ts
  server/routes/index.ts
  server/tests/route.test.ts
Labels: Awaiting Review

#109 107 delete family
  server/controllers/admin/families/deleteFamilyById.ts
  server/controllers/admin/index.ts
  server/controllers/index.ts
  server/middlewares/auth/admin.ts
  server/routes/adminFamily.ts
  server/tests/route.test.ts
Labels: Awaiting Review

#100 86 get/donors/campagin
  server/controllers/admin/campaign/getDonorsByCampaignId.ts
  server/controllers/admin/index.ts
  server/controllers/index.ts
  server/routes/adminDonors.ts
  server/routes/index.ts
  server/tests/route.test.ts
Labels: Awaiting Review

#108 89 patch admin/families/id
  server/controllers/admin/family/editFamily.ts
  server/controllers/admin/index.ts
  server/controllers/index.ts
  server/routes/adminFamilyRoutes.ts
  server/routes/index.ts
  server/tests/route.test.ts
Labels: Awaiting Review

#112 111 get campaigns
  server/controllers/campaigns/getCampaigns.ts
  server/database/models/index.ts
  server/routes/campaign.ts
  server/tests/route.test.ts
Labels: Awaiting Review

#115 Admin Post Campaign
  server/controllers/admin/campaign/createCampaign.ts
  server/controllers/admin/index.ts
  server/routes/campaign.ts
  server/tests/route.test.ts
  server/utils/validation/campaignSchema.ts
  server/utils/validation/index.ts
Labels: Done

#129 90 dashboard
  client/craco.config.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Dashboard/index.jsx
  client/src/components/Dashboard/style.css
  client/src/components/common/Nav/index.jsx
  client/src/pages/Login/index.jsx
  client/src/redux/feature/user/userSlice.js
Labels: Awaiting Review

#113 Admin Get All families
  server/controllers/admin/families/getAllFamilies.ts
  server/controllers/admin/index.ts
  server/controllers/index.ts
  server/database/models/capon.ts
  server/database/models/index.ts
  server/routes/adminFamily.ts
  server/routes/campaign.ts
  server/tests/route.test.ts
Labels: Awaiting Review

#121 Admin Get Family Campaigns
  server/controllers/admin/families/getCampaginsforFamily.ts
  server/controllers/admin/index.ts
  server/routes/adminFamily.ts
  server/tests/route.test.ts
Labels: Awaiting Review

#117 Admin Delete Campaign
  server/controllers/admin/campaign/deleteCampaign.ts
  server/controllers/admin/index.ts
  server/routes/campaign.ts
  server/tests/route.test.ts
Labels: Awaiting Review

#126 Delete contacts route
  server/controllers/admin/index.ts
  server/controllers/index.ts
  server/controllers/reports/deleteReports.ts
  server/routes/reports.ts
  server/tests/route.test.ts
Labels: Awaiting Review

#122 102 get donors route
  server/controllers/admin/donors/getDonors.ts
  server/controllers/admin/index.ts
  server/controllers/index.ts
  server/database/fakeData/buildFakeData.ts
  server/database/models/index.ts
  server/routes/adminDonor.ts
  server/routes/index.ts
  server/tests/route.test.ts
  server/utils/index.ts
Labels: Awaiting Review

#123 119 get donor campaigns route
  server/controllers/admin/donors/getDonorsCampaigns.ts
  server/controllers/admin/index.ts
  server/controllers/index.ts
  server/routes/adminDonor.ts
  server/tests/route.test.ts
Labels: Awaiting Review

#130 Admin Patch Doners
  server/controllers/admin/donors/updateDonorById.ts
  server/controllers/admin/index.ts
  server/controllers/index.ts
  server/routes/adminDonor.ts
  server/tests/route.test.ts
  server/utils/index.ts
  server/utils/validation/donorSchema.ts
  server/utils/validation/index.ts
Labels: Done

#139 91 family
  client/src/App.js
  client/src/components/Family/FamilyButton.jsx
  client/src/components/Family/FamilyForm.jsx
  client/src/components/Family/index.jsx
  client/src/components/Family/style.css
  client/src/components/index.jsx
  server/controllers/admin/families/getAllFamilies.ts
Labels: Awaiting Review

#137 Create Campaigns Table
  client/package-lock.json
  client/src/App.js
  client/src/pages/admin/CampaignsTable/index.jsx
  client/src/pages/admin/CampaignsTable/style.css
  client/src/pages/admin/index.jsx
  client/src/pages/index.jsx
  package-lock.json
  server/controllers/auth/login.ts
  server/controllers/campaigns/getCampaigns.ts
  server/database/config/connection.ts
Labels: Awaiting Review

#131 124 post admin families campaigns
  package-lock.json
  package.json
  server/controllers/admin/campaign/postFamiliesForCampaign.ts
  server/controllers/admin/index.ts
  server/controllers/index.ts
  server/routes/adminCampaign.ts
  server/routes/index.ts
  server/tests/route.test.ts
  server/utils/index.ts
  server/utils/validation/familiesForCampaignSchema.ts
  server/utils/validation/index.ts
Labels: Awaiting Review

#141 Admin Donor Table
  client/public/index.html
  client/public/manifest.json
  client/src/App.js
  client/src/pages/Login/index.jsx
  client/src/pages/admin/DonorsTable/EditDonorModal.jsx
  client/src/pages/admin/DonorsTable/index.jsx
  client/src/pages/admin/DonorsTable/style.less
  client/src/pages/admin/index.jsx
  client/src/pages/index.jsx
  server/routes/adminDonor.ts
Labels: Awaiting Review

#144 Admin Dashboard Reports
  client/src/App.js
  client/src/pages/admin/ReportsTable/index.jsx
  client/src/pages/admin/ReportsTable/style.less
  client/src/pages/admin/index.jsx
  client/src/pages/index.jsx
Labels: Awaiting Review

#152 133 campaign donors table
  client/craco.config.js
  client/src/components/admin/DonorsForCampaignTable/index.js
  client/src/components/admin/DonorsForCampaignTable/style.less
  client/src/components/admin/index.js
  client/src/components/index.jsx
  client/src/pages/admin/CampaignsTable/index.jsx
  server/controllers/admin/campaign/getDonorsByCampaignId.ts
Labels: Awaiting Review

#145 138 add edit campaign
  client/src/App.js
  client/src/components/AddCampaign/AddCampaignForm.js
  client/src/components/AddCampaign/style.css
  client/src/components/index.jsx
  client/src/pages/admin/CampaignsTable/index.jsx
  client/src/pages/admin/CampaignsTable/style.css
  server/controllers/campaigns/getCampaigns.ts
Labels: Awaiting Review

#154 151 overview tables
  .eslintrc.json
  client/src/App.js
  client/src/components/AddFamiliesModal/index.jsx
  client/src/components/TopCampaignsTable/index.jsx
  client/src/components/TopCampaignsTable/style.css
  client/src/components/TopDonorsTable/index.jsx
  client/src/components/index.jsx
  client/src/pages/Error/NotFoundError.jsx
  client/src/pages/Error/ServerError.jsx
  client/src/pages/admin/CampaignsTable/index.jsx
  client/src/pages/admin/DonorsTable/index.jsx
  client/src/pages/index.jsx
  server/controllers/admin/donors/getDonors.ts
  server/controllers/campaigns/getCampaigns.ts
  server/tests/route.test.ts
  server/utils/validation/querySchema.ts
Labels: Awaiting Review

#150 146 bar chart
  client/craco.config.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/CampaginsDonorsChart/index.js
  client/src/components/common/Nav/index.jsx
  client/src/components/index.jsx
  package-lock.json
  package.json
  server/controllers/campaigns/getFilteredCampaign.ts
  server/tests/getAllCampaignsResult.json
  server/tests/route.test.ts
Labels: Awaiting Review

#153 Admin Categories Pie Chart Overview
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/pages/admin/Overview/CategoriesPie/index.jsx
  client/src/pages/admin/Overview/index.jsx
  client/src/pages/admin/index.jsx
  server/controllers/categories/getAllCategories.ts
  server/database/models/index.ts
Labels: Awaiting Review

#162 Fix backend
  server/controllers/admin/families/deleteFamilyById.ts
  server/controllers/donations/addDonation.ts
  server/tests/route.test.ts
Labels: Done
