Repository GSG-G11/Indonate, pull requests merged in 2022-04, with the labels that each got.

#5 create file structure and install packages and eslint
  .env.example
  .eslintrc.json
  .gitignore
  client/.env.example
  client/.eslintrc.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/app/store.js
  client/src/index.js
  package-lock.json
  package.json
  server/app.ts
  server/controllers/index.ts
  server/database/index.ts
  server/index.ts
  server/middlewares/index.ts
  server/routes/index.ts
  server/tests/database.test.js
  server/tests/route.test.js
  server/utils/index.ts
  tsconfig.json
Labels: Awaiting Review

#17 set server
  .eslintrc.json
  client/package.json
  package-lock.json
  package.json
  server/app.ts
  server/index.ts
  server/routes/index.ts
  tsconfig.json
Labels: Awaiting Review

#19 10 error handling
  server/app.ts
  server/middlewares/error/pageNotFoundError.ts
  server/middlewares/error/serverError.ts
  server/middlewares/index.ts
  server/utils/customedError.ts
  server/utils/index.ts
Labels: Awaiting Review

#18 16 setup database
  .env.example
  .eslintrc.json
  package.json
  server/database/config/build.sql
  server/database/config/build.ts
  server/database/config/connection.ts
  server/database/index.ts
  server/database/models/campaign.ts
  server/database/models/capon.ts
  server/database/models/category.ts
  server/database/models/contact.ts
  server/database/models/donation.ts
  server/database/models/donor.ts
  server/database/models/family.ts
  server/database/models/index.ts
Labels: Awaiting Review

#6 Create node.js.yml
  .github/workflows/node.js.yml
Labels: Done

#24 23 fake data
  .eslintrc.json
  package.json
  server/database/fakeData/buildFakeData.ts
  server/database/fakeData/campaigns.json
  server/database/fakeData/capons.json
  server/database/fakeData/categories.json
  server/database/fakeData/contacts.json
  server/database/fakeData/donations.json
  server/database/fakeData/donors.json
  server/database/fakeData/families.json
  server/middlewares/index.ts
  tsconfig.json
Labels: Awaiting Review

#20 POST /login
  .env.example
  .github/workflows/node.js.yml
  jest.config.ts
  package-lock.json
  package.json
  server/controllers/auth/login.ts
  server/controllers/index.ts
  server/database/fakeData/donors.json
  server/routes/authRoutes.ts
  server/routes/index.ts
  server/tests/database.test.ts
  server/tests/route.test.js
  server/tests/route.test.ts
  server/utils/index.ts
  server/utils/signToken.ts
  server/utils/validation/index.ts
  server/utils/validation/loginSchema.ts
  tsconfig.json
Labels: Awaiting Review

#28 27 change antd theme
  client/craco.config.js
  client/package-lock.json
  client/package.json
Labels: Awaiting Review

#29 22 POST/ sign up
  client/package-lock.json
  server/controllers/auth/signUp.ts
  server/controllers/index.ts
  server/routes/authRoutes.ts
  server/routes/index.ts
  server/tests/route.test.ts
  server/utils/index.ts
  server/utils/validation/index.ts
  server/utils/validation/loginSchema.ts
  server/utils/validation/signUpSchema.ts
Labels: Awaiting Review

#32 30 logout
  client/package-lock.json
  server/controllers/auth/logout.ts
  server/controllers/index.ts
  server/routes/authRoutes.ts
  server/tests/route.test.ts
Labels: Awaiting Review

#34 Check User Authentication
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/app/store.js
  client/src/features/User.js
  client/src/pages/index.jsx
Labels: Awaiting Review

#41 39 post reports
  server/controllers/index.ts
  server/controllers/reportsRouter/reports.ts
  server/routes/index.ts
  server/routes/reportsRoutes.ts
  server/tests/route.test.ts
  server/utils/index.ts
  server/utils/validation/index.ts
  server/utils/validation/reportsSchema.ts
Labels: Awaiting Review

#40 38 get campaign
  server/controllers/compaignRouter/getCampaignById.ts
  server/controllers/index.ts
  server/routes/campaignRoutes.ts
  server/routes/index.ts
  server/tests/route.test.ts
  server/utils/index.ts
  server/utils/validation/index.ts
  server/utils/validation/paramsSchema.ts
Labels: Awaiting Review

#48 33 get all categories
  server/controllers/categories/getAllCategories.ts
  server/controllers/index.ts
  server/routes/categoryRoutes.ts
  server/routes/index.ts
  server/tests/route.test.ts
  server/utils/index.ts
  server/utils/validation/index.ts
Labels: Awaiting Review

#25 Sign up component
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Component/assets/images/poor.png
  client/src/Component/signUp/index.jsx
  client/src/Component/signUp/style.css
  client/src/Component/signUp/style.less
  client/src/index.js
  client/src/redux/app/store.js
  client/src/redux/feature/user/userSlice.js
Labels: Awaiting Review

#43 auth user middleware
  server/middlewares/auth/user.ts
  server/utils/index.ts
  server/utils/token/index.ts
  server/utils/token/signToken.ts
  server/utils/token/verifyToken.ts
Labels: Awaiting Review

#42 auth admin middleware
  .vscode/launch.json
  server/middlewares/auth/admin.ts
Labels: Done

#52 Campaign Card Component
  client/package-lock.json
  client/src/Component/common/campaignCard/index.jsx
  client/src/Component/common/campaignCard/index.less
Labels: Done

#55 49 Nav component
  client/craco.config.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Nav/index.jsx
  client/src/components/Nav/style.css
  client/src/components/assets/images/poor.png
  client/src/components/index.jsx
  client/src/components/signUp/index.jsx
  client/src/components/signUp/style.css
  client/src/components/signUp/style.less
  client/src/components/signin/index.jsx
  client/src/components/signin/index.less
  server/utils/validation/index.ts
Labels: Awaiting Review

#47 GET Statistics
  server/controllers/compaignRouter/statistics.ts
  server/controllers/index.ts
  server/database/models/donation.ts
  server/routes/campaignRoutes.ts
  server/routes/index.ts
  server/tests/route.test.ts
Labels: Awaiting Review, Done

#66 36 post donation
  .eslintrc.json
  client/package-lock.json
  server/controllers/donations/addDonation.ts
  server/controllers/index.ts
  server/database/fakeData/donations.json
  server/database/models/donation.ts
  server/database/models/index.ts
  server/routes/donationRoutes.ts
  server/routes/index.ts
  server/tests/route.test.ts
  server/utils/validation/donationSchema.ts
  server/utils/validation/index.ts
Labels: Awaiting Review

#65 62 review card section
  client/package-lock.json
  client/src/App.js
  client/src/components/Review/Comment.jsx
  client/src/components/Review/index.jsx
  client/src/components/Review/style.css
  client/src/components/assets/images/bgImg-comments.jpeg
  client/src/components/common/campaignCard/index.jsx
  client/src/components/common/campaignCard/index.less
  client/src/components/index.jsx
Labels: Done

#31 create checkAuth controllers
  server/controllers/auth/checkAuth.ts
  server/controllers/index.ts
  server/middlewares/index.ts
  server/routes/authRoutes.ts
  server/routes/index.ts
  server/tests/route.test.ts
Labels: Awaiting Review

#54 44 get campaign
  server/controllers/compaignRouter/campaignes.ts
  server/controllers/index.ts
  server/database/fakeData/buildFakeData.ts
  server/database/fakeData/campaigns.json
  server/routes/campaignRoutes.ts
  server/tests/getAllCampainesResult.json
  server/tests/route.test.ts
  server/utils/index.ts
  server/utils/validation/QueryValidation.ts
  server/utils/validation/index.ts
Labels: Done

#73 72 reports section
  client/src/App.js
  client/src/components/ReportsForm/index.jsx
  client/src/components/ReportsForm/style.less
  client/src/components/index.jsx
Labels: Awaiting Review

#59 53 our mission component
  client/package.json
  client/src/App.js
  client/src/assets/our-mission-background.jpg
  client/src/components/OurMission/index.jsx
  client/src/components/OurMission/style.less
  client/src/components/index.jsx
Labels: request-change

#69 create donate form
  client/src/App.js
  client/src/components/common/campaignCard/index.jsx
  client/src/components/donateForm/DonateButton.jsx
  client/src/components/donateForm/DonationForm.jsx
  client/src/components/donateForm/style.css
  client/src/components/index.jsx
  server/utils/validation/donationSchema.ts
Labels: Awaiting Review

#75 57 filter search components
  client/craco.config.js
  client/src/components/filterCampaigns/index.jsx
  client/src/components/filterCampaigns/style.less
  client/src/components/index.jsx
  client/src/components/signUp/style.css
Labels: Awaiting Review
